#!/usr/bin/python

# WRITTEN FOR PYTHON VERSION 2.7.5

import errno
import os
import sys
import json
import codecs
import io
import datetime
import time
import requests
from requests.adapters import HTTPAdapter
from requests.packages.urllib3.poolmanager import PoolManager
import errno

# region File IO
def IO_RealPath(filePath):
    return os.path.realpath(os.path.expanduser(filePath))
def IO_GetEnvironmentDir():
    ENV_NAME = os.getenv("ENV_NAME", os.path.basename(os.path.dirname(os.path.abspath(__file__))))
    return os.path.join("/nfs/stak/users/christj/", ENV_NAME)
def IO_WriteFile(filePath, contents, binary=False):
    filePath = IO_RealPath(filePath)
    if binary:
        with open(filePath, "wb") as f:
            f.write(contents)
    else:
        with codecs.open(filePath, "w", encoding="utf-8") as f:
            f.write(contents)
def IO_AppendFile(filePath, contents, binary=False):
    filePath = IO_RealPath(filePath)
    if binary:
        with open(filePath, "ab") as f:
            f.write(contents)
    else:
        with codecs.open(filePath, "a", encoding="utf-8") as f:
            f.write(contents)
def IO_CreateFile(filePath, contents, mode, binary=False):
    filePath = IO_RealPath(filePath)
    fd = os.open(filePath, os.O_WRONLY | os.O_CREAT | os.O_EXCL, mode)
    try:
        if binary:
            with os.fdopen(fd, "wb") as f:
                f.write(contents)
        else:
            with io.open(fd, "w", encoding="utf-8") as f:
                f.write(contents)
    except Exception:
        try:
            os.close(fd)
        except OSError:
            pass
        raise
def IO_ReadFile(filePath, defaultContents=None, binary=False):
    filePath = IO_RealPath(filePath)
    try:
        if binary:
            with open(filePath, "rb") as f:
                return f.read()
        else:
            with codecs.open(filePath, "r", encoding="utf-8") as f:
                return f.read()
    except IOError as ex:
        if ex.args[0] == errno.ENOENT and defaultContents != None:
            return defaultContents
        else:
            raise
    if defaultContents != None and not os.path.exists(filePath):
        return defaultContents
def IO_SerializeJson(obj, compact=False):
    return json.dumps(obj, separators=(',', ':') if compact else None, indent=None if compact else 4)
def IO_DeserializeJson(jsonString):
    return json.loads(jsonString)
def IO_GetEpoch():
    return time.time()
def IO_FormatEpoch(epoch):
    timestamp = datetime.datetime.fromtimestamp(epoch)
    return timestamp.strftime("%I:%M%p %m/%d").lower()
# endregion

# region Logs
def LOG_Generic(message, log_type):
    formatted_message = "{} - {} {} - {}".format(log_type, IO_FormatEpoch(IO_GetEpoch()), int(IO_GetEpoch()), message)
    log_path = os.path.join(IO_GetEnvironmentDir(), "API.log")
    if not os.path.exists(log_path):
        IO_CreateFile(log_path, "{}\n".format(formatted_message), 0o600)
    else:
        IO_AppendFile(log_path, "{}\n".format(formatted_message))
def LOG_Info(message):
    LOG_Generic(message, "Info")
def LOG_Warning(message):
    LOG_Generic(message, "Warning")
def LOG_Error(message):
    LOG_Generic(message, "ERROR")
def LOG_Exception(ex):
    _, _, tb = sys.exc_info()
    tb_data = None
    while tb is not None:
        if IO_RealPath(tb.tb_frame.f_code.co_filename) == IO_RealPath(__file__):
            message = repr(ex)
            funcname = "<module>" if tb.tb_frame.f_code.co_name == "<module>" else tb.tb_frame.f_code.co_name + "()"
            lineno = tb.tb_lineno
            line = IO_ReadFile(tb.tb_frame.f_code.co_filename).splitlines()[lineno - 1].strip()
            tb_data = { "message": message, "funcname": funcname, "lineno": lineno, "line": line }
        tb = tb.tb_next
    if tb_data == None:
        LOG_Generic("{} at unknown location".format(repr(ex)), "PY_EX")
    else:
        LOG_Generic("{} in {} line {}: {}".format(tb_data['message'], tb_data['funcname'], tb_data['lineno'], tb_data['line']), "PY_EX")
# endregion

# region Environment
ENV = None
def ENV_Load():
    global ENV
    env_path = os.path.join(IO_GetEnvironmentDir(), "environment.json")
    ENV = IO_DeserializeJson(IO_ReadFile(env_path))
# endregion

def Main():
    class HostNameIgnoringAdapter(HTTPAdapter):
        def init_poolmanager(self, connections, maxsize, block=False):
            self.poolmanager = PoolManager(num_pools=connections, maxsize=maxsize, block=block, assert_hostname=False)
    crt_path = os.path.join(IO_GetEnvironmentDir(), "ONIDbot.crt")
    key_path = os.path.join(IO_GetEnvironmentDir(), "ONIDbot.key")
    session = requests.Session()
    session.mount("https://", HostNameIgnoringAdapter())

    for api_host in ENV["api_hosts"]:
        try:
            url = "https://{}:{}/API?{}".format(api_host, ENV["api_port"], os.environ.get("QUERY_STRING", ""))
            response = session.get(url, verify=crt_path, cert=(crt_path, key_path))
            return response.text
        except requests.exceptions.ConnectionError as ex:
            try:
                if ex[0][1].errno == errno.ECONNREFUSED:
                    continue
            except:
                pass
            raise ex
    LOG_Error("CGI Main - All API cluster nodes are down!")
    return IO_SerializeJson({ "state": "error", "title": "An Error Occurred", "message": "Please DM @finlaytheberry to report this issue.<br />Error details: All servers are down. " + ENV["api_port"] }, compact=True)

print("Status: 200")
print("Content-Type: application/json")
print("")
try:
    os.chdir(IO_GetEnvironmentDir())
    ENV_Load()
    print(Main())
except Exception as ex:
    LOG_Exception(ex)
    print(IO_SerializeJson({ "state": "error", "title": "An Error Occurred", "message": "Please DM @finlaytheberry to report this issue.<br />Error details: An internal server error occurred." }, compact=True))
